//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stuff()
        {
            this.Busket = new HashSet<Busket>();
        }
    
        public int ID { get; set; }
        public string Articl { get; set; }
        public string Title { get; set; }
        public Nullable<int> IDUnit { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MaxSale { get; set; }
        public Nullable<int> IDManufacturer { get; set; }
        public Nullable<int> IDProvider { get; set; }
        public Nullable<int> IDType { get; set; }
        public Nullable<int> NowSale { get; set; }
        public Nullable<int> CountInStorage { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Busket> Busket { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual TypeStuff TypeStuff { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
